### ISSUE TITLE
Stack 2.5.1 fails to build on macOS 10.12.6

### ISSUE THREAD

**Issue by debohman** [commercialhaskell/stack#5496]
Using a binary version of stack 2.5.1 downloaded from:

https://haskellstack.org

I cloned the git repository from here, then switched to the v2.5.1 tag.

stack setup
stack build

It builds most of the way, and then runs into a missing symbol during the final link of the tool:

```Building executable 'stack' for stack-2.5.1..
[1 of 4] Compiling Build_stack
[2 of 4] Compiling Paths_stack
[3 of 4] Compiling BuildInfo
[4 of 4] Compiling Main
Linking .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/stack/stack ...
Undefined symbols for architecture x86_64:
  "_utimensat", referenced from:
      _cazW_info in libHSdirectory-1.3.3.0.a(Posix.o)
ld: symbol(s) not found for architecture x86_64
```
I expected the package manager to use the correct version of libHSdirectory-1.3.3.0.a for my OS. At least, it should have failed sooner than the link phase.

stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0

git describe --long
v2.5.1-0-gd6ab8615

**Comment by debohman** [comment]
I worked around the problem by building my own copy of ghc-8.6.5, the version required by the build of stack.

It appears to be a configuration problem with the library 'directory'.

**Comment by debohman** [comment]
This is the version of stack I built:

stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 (8249 commits) x86_64 hpack-0.33.0

**Comment by kencu** [comment]
On macOS, there are a lot of problems with (usually open-source) projects that test for the existence of a certain feature, like utimensat, in -- say -- the SDK, or headers, or some such at configure or build time -- but these features do not exist when these features are looked for at run time (or in this case, at link time). This is why, for example, the upstream ghc version that is supposed to be runnable on 10.7+, actually is not.

I think here in this particular case the issue is that the SDK used on macOS 10.12 is actually the MacOSX10.13.sdk (Apple's usual mode is to supply the next SDK to the system you are running on), which does support utimensat, but when the link happens, the libraries in "/usr/lib" don't actually support that on 10.12, so the link fails.

There are several ways this can be approached.

One way is to weak-link the desired but may-not-exist symbols and test to see if they are available (non-nil) at run time. That works.

Another way is to force off symbols that aren't available on systems back to the floor of your deployment target. For example, force utimensat off, even if it is available in the build SDK, so that it won't be looked for at run time. This also works, and is probably simpler, if a bit disappointing.

Apple has another way in the clang source now, using the "@available()" functions, but this capability would have to be written into GHC.

What I do is build ghc, stack, and cabal on macOS 10.6, and in so doing, they run on everything from 10.6 to the newest systems.

**Comment by debohman** [comment]
It seems to me that a fix needs to be made to the 'directory' library for macOS in GHC, or that GHC needs to built on a release before high sierra. It needs to avoid trying to invoke the utimensat() system call, since it is not implemented before high sierra. Either that, or say that GHC is not supported before high sierra.

When stack downloads a particular compiler version, where is it getting the binaries from? Are they stack specific, or binary distributions from GHC?

Also note that GHC does not use macOS SDKs to build, it uses the GNU autoconf system.

**Comment by kencu** [comment]
> It seems to me that a fix needs to be made to the 'directory' library for macOS in GHC, or that GHC needs to be built on a release before high sierra. It needs to avoid trying to invoke the utimensat() system call, since it is not implemented before high sierra. Either that, or say that GHC is not supported before high sierra.

ghc works great on all systems from 10.6.8 up. But as I said, I build it on 10.6.8.


> 
> When stack downloads a particular GHC version, where is it getting the binaries from? Are they stack specific, or binary distributions from GHC?

binary distributions from a GHC builder member (Ben), build on a current system with a deployment target of 10.7. That probably used to work, it doesn't now.


> 
> Also note that GHC does not use macOS SDKs to build, it uses the GNU autoconf system.

It uses autoconf, but nothing can build without an SDK of course, because that is where the headers and libraries are :>

**Comment by debohman** [comment]
The stack 2.5.1 binary which I downloaded runs fine on my system. When I tried to rebuild it as a exercise, it downloaded a ghc-8.6.5 binary which was obviously built against high sierra or later, hence this bug report.

By SDK, I meant an Xcode SDK.

To be honest, I am not sure why nanosecond timestamp resolution is necessary in this library for portability sake.

Should I file a bug against GHC?

**Comment by kencu** [comment]
> The stack 2.5.1 binary which I downloaded runs fine on my system. When I tried to rebuild it as a exercise, it downloaded a ghc-8.6.5 binary which was obviously built against high sierra or later, hence this bug report.

On macOS, there are a lot of problems with (usually open-source) projects that test for the existence of a certain feature, like utimensat, in -- say -- the SDK, or headers, or some such at configure or build time -- but these features do not exist when these features are looked for at run time (or in this case, at link time). This is why, for example, the upstream ghc version that is supposed to be runnable on 10.7+, actually is not


> 
> By SDK, I meant an Xcode SDK.
> 

On macOS, those are the only kind of SDKs that there are. 

> Should I file a bug against GHC?


You could -- that would most likely get them to just drop all support for macOS systems < 10.13, I would think.

**Comment by mpilgrem** [comment]
Closing as it now relates to a legacy version of Stack.
