### ISSUE TITLE
Build with flag(disable-git-info) fails

### ISSUE THREAD

**Issue by bjin** [commercialhaskell/stack#6125]
I was building a [statically linked aarch64 stack binary](https://github.com/bjin/stack-aarch64-static/) for use with aarch64 alpine docker, since I was grabbing tarball file from releases page instead of `git clone`, I thought it might be better to disable git hash to avoid confusing. But I encountered following compilation error:

```
/home/circleci/project/stack-2.11.1/src/main/BuildInfo.hs:48:18: error:
    Variable not in scope: showStackVersion :: [Char]
   |
48 | versionString' = showStackVersion ++ afterVersion
   |                  ^^^^^^^^^^^^^^^^
```

It seems that the offending commit is https://github.com/commercialhaskell/stack/commit/43b1210a5316f5e1131c3be0cb6989290ffbef8d. The import list of `src/main/BuildInfo.hs` is not changed accordingly in `USE_GIT_INFO` guard.

**Comment by mpilgrem** [comment]
@bjin Thanks for reporting. I'm tied up for a few days but will then fix this. Something also needs to be added to the CI tests so that this sort of slip is picked up in the future.
