### ISSUE TITLE
1.9.3 fails to build with rio 0.1.9.0

### ISSUE THREAD

**Issue by felixonmars** [commercialhaskell/stack#4724]
Version bounds are currently >= 0.1.5.0 && < 0.2, but stack 1.9.3 fails to build with rio 0.1.9.0. Might need to adjust the bounds.

```
[ 55 of 127] Compiling Text.PrettyPrint.Leijen.Extended ( src/Text/PrettyPrint/Leijen/Extended.hs, dist/build/Text/PrettyPrint/Leijen/Extended.dyn_o )

src/Text/PrettyPrint/Leijen/Extended.hs:144:14: error:
    Ambiguous occurrence ‘empty’
    It could refer to either ‘Text.PrettyPrint.Annotated.Leijen.empty’,
                             imported from ‘Text.PrettyPrint.Annotated.Leijen’ at src/Text/PrettyPrint/Leijen/Extended.hs:130:1-63
                          or ‘Stack.Prelude.empty’,
                             imported from ‘Stack.Prelude’ at src/Text/PrettyPrint/Leijen/Extended.hs:127:1-42
                             (and originally defined in ‘GHC.Base’)
    |
144 |     mempty = empty
    |              ^^^^^
```

**Comment by qrilka** [comment]
Yep, that was already noticed, thanks for your report

**Comment by snoyberg** [comment]
We've released a 0.1.9.1 point release of `rio` to remove the accidentally exported `empty` identifier.

**Comment by qrilka** [comment]
@snoyberg that one is just 1 of the existing incompatibilities...

**Comment by snoyberg** [comment]
Can you clarify what you mean by that?

**Comment by felixonmars** [comment]
@snoyberg I believe he means the MonadFail.fail change, which I encountered with 0.1.9.0 patched to remove the empty identifier.

**Comment by snoyberg** [comment]
Reopening, thanks for the clarification @felixonmars.

For the record: we don't support building Stack with versions of dependencies not listed in one of the stack.yaml files. Is this by any chance for an Arch Linux release?

**Comment by felixonmars** [comment]
I believe the hackage bounds indicate some level of support as well, currently that's how Arch Linux do packaging for stack. In stack.yaml every dependency is considered pinned to a possibly old version, which won't work for distribution packaging.

**Comment by borsboom** [comment]
For uploading `stack` to Hackage we use a variant of `--pvp-bounds=both`, which allows for building it with more recent minor versions of dependencies.

I've now updated the cabal metadata on hackage to only allow < 0.1.9.0.

**Comment by snoyberg** [comment]
Point release 1.9.3.1 is now on Hackage, closing
