### PR TITLE
Rename PathException to InvalidPathException to avoid conflict with path 0.6+

### LINKED ISSUE #3223: Doesn't build with path 0.6
```
[ 11 of 124] Compiling System.Process.Read ( src/System/Process/Read.hs, dist/build/System/Process/Read.o )

src/System/Process/Read.hs:429:20: error:
    Ambiguous occurrence ‘PathException’
    It could refer to either ‘Path.PathException’,
                             imported from ‘Path’ at src/System/Process/Read.hs:69:1-21
                          or ‘System.Process.Read.PathException’,
                             defined at src/System/Process/Read.hs:426:1

src/System/Process/Read.hs:430:15: error:
    Ambiguous occurrence ‘PathException’
    It could refer to either ‘Path.PathException’,
                             imported from ‘Path’ at src/System/Process/Read.hs:69:1-21
                          or ‘System.Process.Read.PathException’,
                             defined at src/System/Process/Read.hs:426:1
```

### PR DESCRIPTION
**Pull request by felixonmars**
Fixes #3223

Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks!
