### ISSUE TITLE
Cannot build using GHC 8.10.7 and cabal-install 3.6.2.0 on aarch64 Linux

### ISSUE THREAD

**Issue by fwcd** [commercialhaskell/stack#5684]
### General summary/comments (optional)

Stack fails to build using GHC 8.10.7 and cabal-install 3.6.2.0 on aarch64 Arch Linux.

### Steps to reproduce

For example:

1. Use the OS and GHC/Cabal versions given above.
2. Run `cabal new-build`. 

### Expected

Stack should build.

### Actual

```
[ 30 of 111] Compiling Stack.Types.Resolver ( src/Stack/Types/Resolver.hs, dist/build/Stack/Types/Resolver.o, dist/build/Stack/Types/Resolver.dyn_o )

src/Stack/Types/Resolver.hs:90:34: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap
                             aeson-2.0.3.0:Data.Aeson.Types.Internal.Value’
                     with ‘HashMap Text aeson-2.0.3.0:Data.Aeson.Types.Internal.Value’
      Expected type: HashMap
                       Text aeson-2.0.3.0:Data.Aeson.Types.Internal.Value
        Actual type: aeson-2.0.3.0:Data.Aeson.Types.Internal.Object
    • In the first argument of ‘HashMap.toList’, namely ‘o’
      In the second argument of ‘($)’, namely ‘HashMap.toList o’
      In the second argument of ‘($)’, namely
        ‘filter (isLTS . fst) $ HashMap.toList o’
   |
90 |                 $ HashMap.toList o)
   |                                  ^
cabal: Failed to build stack-2.7.4. See the build log above for details.
```

### Method of installation

* Via cabal-install

**Comment by fwcd** [comment]
Since this seems to be due to an API change in one of the dependencies, I'll check whether #5677 fixes the issue.

**Comment by Bodigrim** [comment]
As a Hackage trustee, I made a revision fixing this: https://hackage.haskell.org/package/stack-2.7.5/revisions/

**Comment by juhp** [comment]
I think this can be closed
