### ISSUE TITLE
Regression for doctest in 2.1.1

### ISSUE THREAD

**Issue by eborden** [commercialhaskell/stack#4861]
### General summary/comments (optional)

After switching to 2.1.1 I'm seeing the need to include `-package [package-name]` in `doctest` flags. This was not previously necessary.

### Steps to reproduce

I do not yet have a minimal reproduction.

### Expected

I would expect not to need the `-package` flag.

### Actual

```
fancy-api> test (suite: doctest)

Loaded package environment from /tmp/stack3123/test-ghc-env
Loaded package environment from /tmp/stack3123/test-ghc-env

library/FrontRow/Api/School/TextSearch/Internal.hs:23:1: error:
    Could not load module 'Import'
    It is a member of the hidden package 'fancy-api-0.0.0'.
    You can run ':set -package fancy-api' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v to see a list of the files searched for.
   |
23 | import Import hiding (first, second, toQuery)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

library/FrontRow/Api/School/TextSearch/Internal.hs:30:1: error:
    Could not load module 'FrontRow.Api.TextSearch'
    It is a member of the hidden package 'fancy-api-0.0.0'.
    You can run ':set -package fancy-api' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v to see a list of the files searched for.
   |
30 | import qualified FrontRow.Api.TextSearch as TextSearch
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

fancy-api> Test suite doctest failed
```

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dbaynard** [comment]
Thanks for reporting; I'll take a look and get back to you!

**Comment by junjihashimoto** [comment]
It seems doctests work in 2.2.0.

```
$ stack --version
Version 2.2.0, Git revision f6258124cff9a7e92bcb5704164a70e149080e88 (dirty) (7597 commits) x86_64 hpack-0.31.1
```

**Comment by dbaynard** [comment]
I _think_ I can reproduce this on 2.1.1 for my [mtags](https://github.com/dbaynard/mtags/blob/develop) package, but I get a slightly different error. @eborden would you like to give 2.2.0 a go?

**Comment by dbaynard** [comment]
@eborden As described at https://github.com/commercialhaskell/stack/issues/4896#issuecomment-504646318 you need to ensure that the test dependencies are listed in the test stanza of the package cabal file (or equivalent hpack file).

It would be good if you could provide that sort of information with any future issues you report.

**Comment by neongreen** [comment]
Note: if you are getting `Variable not in scope: polyQuickCheck` when running doctests, you need to add `QuickCheck` to your doctests' `build-depends`.
