### ISSUE TITLE
stack ghci at global level missing base

### ISSUE THREAD

**Issue by MarcelineVQ** [commercialhaskell/stack#3589]
Something recent, possibly the 5b58500830f147eae65da0787571023aecdefc6b commit, is causing errors such as:
```
 <interactive>:1:19: error:
    Not in scope: ‘System.IO.hSetBuffering’
    No module named ‘System.IO’ is imported.

<interactive>:1:43: error:
    Not in scope: ‘System.IO.stdin’
    No module named ‘System.IO’ is imported.

<interactive>:1:60: error:
    Not in scope: data constructor ‘System.IO.NoBuffering’
    No module named ‘System.IO’ is imported.
```
When `stack ghci` is ran outside of any project's scope. These are resolved by specifying  
`stack ghci --package base`

**Comment by snoyberg** [comment]
I think this is affecting intero as well, which recently stopped working for me. CC @mgsloan

**Comment by mgsloan** [comment]
Fixed in https://github.com/commercialhaskell/stack/commit/196bdbae986ddf887f92999b26129085a8ed0be5 thanks for the report @MarcelineVQ !

**Comment by effectfully** [comment]
I did `stack upgrade --git`, but I still see those errors about `System.IO`.

Here is how you can reproduce:

stack.yaml:

```
resolver: lts-9.13
```

nobase-bug.cabal:

```
name:                nobase-bug
version:             0.1.0.0
build-type:          Simple
cabal-version:       >= 1.2

executable nobase-bug
  hs-source-dirs:      src
  main-is:             Main.hs
  default-language:    Haskell2010
  default-extensions:  NoImplicitPrelude
  build-depends:       rerebase
```

src/Main.hs:

```
module Main where

import Prelude

main = return ()
```

**Comment by mgsloan** [comment]
@effectfully Are you sure that the stack binary written by `upgrade` is on your path?  Ensure that `stack --version` reports 1.7.0

**Comment by effectfully** [comment]
@mgsloan, I checked it before reporting. Here is the output of `stack --version`:

```
Version 1.7.0, Git revision 6b9da26bf17c682a5db583f1a5484d4762467a82 x86_64 hpack-0.20.0
```

**Comment by mgsloan** [comment]
Huh!  For me NoImplicitPrelude works with ghci 8.0.2 .  I don't suppose `stack ghc -- --version` reports something else?

You might try switching to lts-10 (ghc 8.2).  I can't find it now but IIRC there was a bug in ghc's tracker about NoImplicitPrelude + ghci.  There is still a bug there for ghci + -XSafe

**Comment by effectfully** [comment]
`stack ghc -- --version` reports GHC is `8.0.2`. `NoImplicitPrelude` + GHC-8.0.2 has been working just fine for me for month.

The funny thing is that if you comment out `build-depends: rerebase`, then `stack ghci` runs without any problems. Sorry, should have said this. So that dependency is crucial somehow. Do you have any ideas? A bug in GHC?

**Comment by snoyberg** [comment]
Sounds like `ghci` is getting confused about which `System.IO` to use, since `rerebase` is providing its own.

**Comment by effectfully** [comment]
@snoyberg, the errors would different then:

```
<interactive>:1:6: error:
    Not in scope: ‘System.IO.hSetBuffering’
    No module named ‘System.IO’ is imported.

<interactive>:1:30: error:
    Not in scope: ‘System.IO.stdin’
    No module named ‘System.IO’ is imported.

<interactive>:1:46: error:
    Not in scope: data constructor ‘System.IO.NoBuffering’
    No module named ‘System.IO’ is imported.

<interactive>:1:70: error:
    Not in scope: ‘System.IO.hSetBuffering’
    No module named ‘System.IO’ is imported.

<interactive>:1:94: error:
    Not in scope: ‘System.IO.stdout’
    No module named ‘System.IO’ is imported.

<interactive>:1:111: error:
    Not in scope: data constructor ‘System.IO.NoBuffering’
    No module named ‘System.IO’ is imported.

<interactive>:1:135: error:
    Not in scope: ‘System.IO.hSetBuffering’
    No module named ‘System.IO’ is imported.

<interactive>:1:159: error:
    Not in scope: ‘System.IO.stderr’
    No module named ‘System.IO’ is imported.

<interactive>:1:176: error:
    Not in scope: data constructor ‘System.IO.NoBuffering’
    No module named ‘System.IO’ is imported.
```

**Comment by effectfully** [comment]
When I start `intero` and write `import Prelude`, I get `Ambiguous interface for 'Prelude'`, so there is indeed some confusion, but `:load` in plain `ghci` works just fine.

I'm currently using `intero` as a text editor rather than an IDE and it's extremely annoying, I don't want to switch back to the `cabal` ecosystem just because there is a single bug, but this bug is total show stopper for me. Could you at least reopen the issue?

**Comment by mgsloan** [comment]
Sure.

What do you get for `stack ghci -v`?  It will tell you how it is invoking ghci, please try to figure out how the invocation needs to change.

What do you get for `stack exec -- ghc-pkg describe base` ?

**Comment by effectfully** [comment]
I get

```
Run process: /home/effectfully/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --interactive -i -odir=/home/effectfully/code/nobase-bug/.stack-work/odir -hidir=/home/effectfully/code/nobase-bug/.stack-work/odir -hide-all-packages -package base -XNoImplicitPrelude -i/home/effectfully/code/nobase-bug/src -i/home/effectfully/code/nobase-bug/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/autogen -i/home/effectfully/code/nobase-bug/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build -i/home/effectfully/code/nobase-bug/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/nobase-bug/nobase-bug-tmp -stubdir=/home/effectfully/code/nobase-bug/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build -package-id=rerebase-1.0.3-GUoprUfp95pIfBD9KsEXFK -optP-include -optP/tmp/ghci26488/cabal_macros.h -ghci-script=/tmp/ghci26488/ghci-script
```

for `stack ghci -v`. I see `-package base` there, can this be a culprit?

`stack exec -- ghc-pkg describe base` results in

```
name: base
version: 4.9.1.0
...
```

[Here](http://lpaste.net/943874932230586368) is full output.

I started to use `-XPackageImports` and even though `intero` "exits abnormally with code 1", type checking, go-to-definition and other tools except `ghci` work, so it's not a show stopper for me anymore. Still would be nice to get `ghci` working ofc.

**Comment by mgsloan** [comment]
Ah, this is indeed caused by https://github.com/commercialhaskell/stack/commit/196bdbae9

The issue is that ghci doesn't start unless something providing these System.IO functions is in scope.

I fixed it! https://github.com/commercialhaskell/stack/commit/99950cfae2e014f76abbebd51869e5cae5f00a6a

**Comment by effectfully** [comment]
I've checked, it works. Thank you.

**Comment by mgsloan** [comment]
Welcome! Thanks for verifying
