### ISSUE TITLE
stack-1.9.3.1 does not compile with persistent-2.10.0 et al

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#4760]
We are seeing the following build error at https://build.opensuse.org/package/live_build_log/devel:languages:haskell:ghc-8.6.x/stack/openSUSE_Tumbleweed/x86_64:

~~~
[  322s] src/Stack/Docker/GlobalDB.hs:36:1: error:
[  322s]     Generating Persistent entities now requires the 'UndecidableInstances' language extension. Please enable it in your file by copy/pasting this line into the top of your file: 
[  322s] 
[  322s] {-# LANGUAGE UndecidableInstances #-}
[  322s]    |
[  322s] 36 | share [mkPersist sqlSettings, mkMigrate "migrateTables"] [persistLowerCase|
[  322s]    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
~~~

**Comment by borsboom** [comment]
That's correct.  The bounds on Hackage specify persistent < 2.10, and the `stack.yaml` specifies `persistent-2.7.1`, so there's no expectation that `stack` should build with persistent-2.10.

@qrilka Looks like we may need to cut a new hackage-only release to support persistent-2.10.

**Comment by snoyberg** [comment]
Closing, the bounds are correct, and we have a new release out.
