### ISSUE TITLE
Support for building with ghc-8.8.1

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#5132]
All my attempts to build `stack` with `ghc-8.8.1` have failed. `cabal install stack` will usually fail while compiling `pantry` and I am not aware of any way to work around or fix that issue.

openSUSE Linux is about to switch to `ghc-8.8.1`, which means that the distribution can no longer compile `stack`. So we would have to drop the tool from our distribution, which feels like a shame.

Could you please advice what to do about this situation?

**Comment by jwaldmann** [comment]
The error is
```
[ 5 of 18] Compiling Pantry.Types     ( src/Pantry/Types.hs, dist/build/Pantry/Types.o )                             
                                                          
src/Pantry/Types.hs:133:1: error:    
    Could not find module ‘Distribution.Compat.ReadP’     
    Perhaps you meant                                     
      Distribution.Compat.Graph (from Cabal-3.0.1.0)                                                                 
      Distribution.Compat.Lens (from Cabal-3.0.1.0)                                                                  
      Distribution.Compat.Stack (from Cabal-3.0.1.0)      
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.                                           
    |                                                                                                                
133 | import qualified Distribution.Compat.ReadP as Parse                                                            
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

src/Pantry/Types.hs:135:1: error:
    Could not find module ‘Distribution.Parsec.Common’
    Perhaps you meant
      Distribution.Parsec.Error (from Cabal-3.0.1.0)
      Distribution.Parsec.Position (from Cabal-3.0.1.0)
      Distribution.Parsec.Warning (from Cabal-3.0.1.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
135 | import Distribution.Parsec.Common (PError (..), PWarning (..), showPos)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build pantry-0.2.0.0 (which is required by stack-2.1.3.1).


```

**Comment by qrilka** [comment]
That one is merged and #5167 should make Stack buildable with GHC-8.8.2

**Comment by jwaldmann** [comment]
> cabal install stack will usually fail while compiling pantry

I was running into this recently. I found this simple work-around (after too many failed attempts - that's why I am documenting it here)

get sources off hackage via `cabal unpack stack`,  go to https://hackage.haskell.org/package/stack , find the date where this was uploaded to/built on hackage, and put that date in `cabal.project`:
```
packages: .

index-state: 2019-07-16T20:16:22Z
```
then build with the compiler that's mentioned in the build log (in that case, 8.6.3) so you get the exact versions of hardwired packages. 

This won't solve the problem "build with ghc-8.8.?" but it solves the bootstrapping problem "build stack from source". Note that the resulting `stack` executable can be used fine to build stack projects with ghc-8.8.?

**Comment by arrowd** [comment]
Stack compiles fine with GHC 8.8.3 on FreeBSD.  This can be closed, I guess.

**Comment by jwaldmann** [comment]
Well `cabal install` with ghc-8.8.3 and current hackage gives 
```
src/Stack/Types/Resolver.hs:71:17: error:
    Ambiguous occurrence ‘SnapName’
```
for me. This way of building *is* inherently unreliable. I mean, that's exactly the problem that `stack` solves.

Still, I think  this is the right goal  https://hackage.haskell.org/package/stack `This package on Hackage is provided for convenience and bootstrapping purposes` but it is currently not met.
