### ISSUE TITLE
stack build --profile linker errors with -debug

### ISSUE THREAD

**Issue by AndrewBate** [commercialhaskell/stack#4970]
### Steps to reproduce
1. stack new 
2. add  -debug to ghc options executable 
3. stack build --profile

[stackerr.zip](https://github.com/commercialhaskell/stack/files/3414011/stackerr.zip)

For example:

### Expected

Build success or an error message stating that --profile & -debug are incompatible

### Actual

Linker error starts with 
```/usr/bin/ld.gold: error: cannot find -lHSrts_thr_debug_p```

```
-*- mode: compilation; default-directory: "~/stack_err/stackerr/" -*-
Compilation started at Sat Jul 20 22:29:29

stack build --profile
Building all executables for `stackerr' once. After a successful build of all of them, only specified executables will be rebuilt.
stackerr> configure (lib + exe)
Configuring stackerr-0.1.0.0...
stackerr> build (lib + exe)
Preprocessing library for stackerr-0.1.0.0..
Building library for stackerr-0.1.0.0..
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_stackerr
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_stackerr
Preprocessing executable 'stackerr-exe' for stackerr-0.1.0.0..
Building executable 'stackerr-exe' for stackerr-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_stackerr
Linking .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/stackerr-exe/stackerr-exe ...
/usr/bin/ld.gold: error: cannot find -lHSrts_thr_debug_p
.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/stackerr-exe/stackerr-exe-tmp/Main.p_o:ghc_5.c:Main_main_info: error: undefined reference to 'era'
.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/stackerr-exe/stackerr-exe-tmp/Main.p_o:ghc_5.c:Main_main_info: error: undefined reference to 'era'
```
Followed by many pages of linker errors

### Stack version

andrew@zarpedon:~/stack_err/stackerr$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2

### Method of installation
* stack upgrade (from official original install)

**Comment by dbaynard** [comment]
Hi, thanks for the report. What platform are you using?

Your zip works fine on 2.1.1 – I'm just trying to reproduce on 2.1.3.

**Comment by AndrewBate** [comment]
Ubuntu 18.04
stack lts-13.29 (ghc-8.6.5)
also fails with lts-12.25 (ghc-8.4.4)  lts-11.19(ghc-8.2.2)
All haskell binaries and runtime systems installed on my machine were installed via stack

```
andrew@zarpedon:~/stack_err/stackerr$ uname --a
Linux zarpedon 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

On my system stack didn't install an rts with both debug and profiling

```
andrew@zarpedon:~$ find ~/  -name 'libHSrts_thr_debug_p.*' 
find: ‘/home/andrew/.dbus’: Permission denied
find: ‘/home/andrew/.cache/dconf’: Permission denied
andrew@zarpedon:~$ find ~/  -name 'libHSrts_thr_debug.*' 
/home/andrew/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/rts/libHSrts_thr_debug.a
/home/andrew/.stack/programs/x86_64-linux/ghc-8.6.5/lib/ghc-8.6.5/rts/libHSrts_thr_debug.a
find: ‘/home/andrew/.dbus’: Permission denied
find: ‘/home/andrew/.cache/dconf’: Permission denied
andrew@zarpedon:~$ 
```

**Comment by dbaynard** [comment]
I get the same `find` result as you, though I don't have the issues. Hmm.

**Comment by JoseD92** [comment]
Hi I get the same issue as @AndrewBate, I will add a full log of the error.
[log.txt](https://github.com/commercialhaskell/stack/files/3502960/log.txt)

my stack version is `Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2` but also get the same error on another machine with stack 2.1.3 both running arch linux and lts-14.1

@dbaynard if you want me to run any test for you just ask

**Comment by dbaynard** [comment]
I'm not sure what's going on, here. Perhaps try changing the linker?

What's (non-personal info) in your `~/.stack/config.yaml`?

**Comment by AndrewBate** [comment]
I get the same error running `stack ghc -- Main.hs -debug -prof` suggesting stack build is not at fault here

[Main.hs.txt](https://github.com/commercialhaskell/stack/files/3526783/Main.hs.txt)


[log.txt](https://github.com/commercialhaskell/stack/files/3526780/log.txt)
