### ISSUE TITLE
stack-1.6.3 fails to build with hpack-0.27.0

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#3871]
```
src/Stack/Package.hs:1372:31: error:
    • Couldn't match expected type ‘Hpack.Force -> IO Hpack.Result’
                  with actual type ‘IO Hpack.Result’
    • The function ‘Hpack.hpackResult’ is applied to two arguments,
      but its type ‘Hpack.Options -> IO Hpack.Result’ has only one
      In the second argument of ‘($)’, namely
        ‘Hpack.hpackResult (Just $ toFilePath pkgDir) Hpack.NoForce’
      In a stmt of a 'do' block:
        r <- liftIO
               $ Hpack.hpackResult (Just $ toFilePath pkgDir) Hpack.NoForce
     |
1372 |                 r <- liftIO $ Hpack.hpackResult (Just $ toFilePath pkgDir) Hpack.NoForce
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stack/Package.hs:1372:50: error:
    • Couldn't match expected type ‘Hpack.Options’
                  with actual type ‘Maybe FilePath’
    • In the first argument of ‘Hpack.hpackResult’, namely
        ‘(Just $ toFilePath pkgDir)’
      In the second argument of ‘($)’, namely
        ‘Hpack.hpackResult (Just $ toFilePath pkgDir) Hpack.NoForce’
      In a stmt of a 'do' block:
        r <- liftIO
               $ Hpack.hpackResult (Just $ toFilePath pkgDir) Hpack.NoForce
     |
1372 |                 r <- liftIO $ Hpack.hpackResult (Just $ toFilePath pkgDir) Hpack.NoForce
     |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^
```

cc @sol FYI

**Comment by sol** [comment]
For reference: https://github.com/commercialhaskell/stack/pull/3867

Anything else we want do here, or can we close this issue?

**Comment by juhp** [comment]
A release? :)

**Comment by borsboom** [comment]
I'll cherry-pick #3867 to the `release` branch and make a Hackage-only patchlevel release.

**Comment by juhp** [comment]
Okay, cool - thanks!

**Comment by borsboom** [comment]
http://hackage.haskell.org/package/stack-1.6.3.1 hask been uploaded.
