### ISSUE TITLE
Doesn't build with path 0.6.1

### ISSUE THREAD

**Issue by felixonmars** [commercialhaskell/stack#3239]
```
[ 16 of 124] Compiling Network.HTTP.Download.Verified ( src/Network/HTTP/Download/Verified.hs, dist/build/Network/HTTP/Download/Verified.o )

src/Network/HTTP/Download/Verified.hs:246:16: error:
    Ambiguous occurrence ‘<.>’
    It could refer to either ‘Path.<.>’,
                             imported from ‘Path’ at src/Network/HTTP/Download/Verified.hs:55:1-24
                          or ‘System.FilePath.<.>’,
                             imported from ‘System.FilePath’ at src/Network/HTTP/Download/Verified.hs:58:38-42
                             (and originally defined in ‘System.FilePath.Posix’)
```
