### ISSUE TITLE
Doesn't build with path 0.6

### ISSUE THREAD

**Issue by felixonmars** [commercialhaskell/stack#3223]
```
[ 11 of 124] Compiling System.Process.Read ( src/System/Process/Read.hs, dist/build/System/Process/Read.o )

src/System/Process/Read.hs:429:20: error:
    Ambiguous occurrence ‘PathException’
    It could refer to either ‘Path.PathException’,
                             imported from ‘Path’ at src/System/Process/Read.hs:69:1-21
                          or ‘System.Process.Read.PathException’,
                             defined at src/System/Process/Read.hs:426:1

src/System/Process/Read.hs:430:15: error:
    Ambiguous occurrence ‘PathException’
    It could refer to either ‘Path.PathException’,
                             imported from ‘Path’ at src/System/Process/Read.hs:69:1-21
                          or ‘System.Process.Read.PathException’,
                             defined at src/System/Process/Read.hs:426:1
```
