### PR TITLE
Fix #6934 Depend on `semaphore-compat-2.0.0`

### LINKED ISSUE #6934: Support semaphore-compat 2.0.0
Related resources:
* https://well-typed.com/blog/2026/06/haskell-ecosystem-report-march-may-2026/#semaphores-and--jsem
* https://gitlab.haskell.org/ghc/ghc/-/merge_requests/15729
* https://gitlab.haskell.org/ghc/semaphore-compat/-/merge_requests/8
* Cabal (the tool) https://github.com/haskell/cabal/pull/11628

---
Stack no longer compiles with semaphore-compat 2.0.0 (GHC 9.12.5-rc2):

```
[155 of 217] Compiling Stack.Build.ExecuteEnv ( src/Stack/Build/ExecuteEnv.hs, dist/build/Stack/Build/ExecuteEnv.o, dist/build/Stack/Build/ExecuteEnv.dyn_o )
src/Stack/Build/ExecuteEnv.hs:122:22: error: [GHC-61689]
    Module ‘System.Semaphore’ does not export ‘Semaphore’.
    |
122 |                    ( Semaphore, destroySemaphore, freshSemaphore )
    |                      ^^^^^^^^^

src/Stack/Build/ExecuteEnv.hs:122:33: error: [GHC-61689]
    Module ‘System.Semaphore’ does not export ‘destroySemaphore’.
    |
122 |                    ( Semaphore, destroySemaphore, freshSemaphore )
    |                                 ^^^^^^^^^^^^^^^^

```

### PR DESCRIPTION
**Pull request by mpilgrem**
See:
* #6934

This pull request is draft until Stackage LTS Hackage (and, consequently, Stack) moves to GHC version that depends on `semaphore-compat > 2.0.0`.

(Not `semaphore-compat > 1.0.0` because `semaphore-compat-2.0.0` has a bug on macOS.)

* [x] Any changes that could be relevant to users have been recorded in ChangeLog.md.
* [x] The documentation has been updated, if necessary

Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on:
* Windows 11
* macOS 26.5.1/AArch64
* Ubuntu 24.04.1 LTS (via WSL2)
* Alpine Linux 3.24.1 (via WSL2)

### CODE REVIEW

**Comment by mpilgrem** [comment]
The CI fails (as expected) because this version of Stack needs to be built with `stack-ghc-9.12.5.yaml` on a system where Stack has previously installed GHC 9.12.5-rc2.

**Comment by mpilgrem** [comment]
Some illustrative (non-scientific) performance metrics, based on building `stack` itself (which has 217 modules), after dependencies have already been compiled, using `Measure-Command` (TotalSeconds) on Windows/PowerShell and `time` on Unix-like operating systems. (Using a local patched `semaphore-compat-2.0.0` on macOS.)

Platform | Windows 11 | macOS 26.5.1/AArch64 | Ubuntu 24.04.1 LTS (via WSL2) | Alpine Linux 3.24.1 (via WSL2)
---------|------------|----------------------|-------------------------------|-------------------
`build --no-semaphore` | 115.24 | 98% cpu 1:46.26 total | real 2m5.487s | real 2m 7.36s
`build --semaphore` | 76.34 | 218% cpu 1:03.01 total | real 1m20.739s | real 1m 24.13s
Wall clock saving | 34% | 41% | 36% | 34%
